### ISSUE TITLE
Support for Money cents?

### ISSUE THREAD

**Issue by KelseyDH** [mbulat/plutus#103]
Love the gem, looks very clean and free of too much magic.   However my project uses ruby Money with `cents` rather than `BigDecimal`, so I would be hesitant to muck around with different representations of money within the same app.

How hard would it be to make Plutus [play nice with rails-money, which uses cents?](https://github.com/RubyMoney/money-rails)

**Comment by mbulat** [comment]
You can have the money gem generate a `BigDecimal` via `money.amount` and feed that into plutus...

``` ruby
entry = Plutus::Entry.build(
                :description => "Order placed for widgets",
                :debits => [
                  {:account_name => "Cash", :amount => money.amount}],
                :credits => [
                  {:account_name => "Unearned Revenue", :amount => money.amount}])
```

And I believe that `Money.from_amount` will allow you to pass in the BigDecimal to convert back
