### ISSUE TITLE
Making Single Entry to account that shows as opening balance

### ISSUE THREAD

**Issue by coderbhairishav** [mbulat/plutus#113]
Is it possible to add a specific opening balance on either side of credit or debit. As per the docs  we need to clear out the debit and credit total with different account.

**Why this feature.**
 So moving to the erp developed on web is it possible to make an entry as opening amount from new Financial Year. 

I can make a separate model that can handle this but I'm curious to know if this is present in library.

**Comment by qoyod-zellwwf** [comment]
Even opening amounts have a credit/debit. That's the whole point of double entry. 


If i understood you correctly, you are looking to write an entry that represents the 'starting balance' of an entity, on a specific date. I don't think that's possible.
Else if you are looking for a feature that simplifies life (where we can assign a default cr account for whatever), then I think that's a bit out of scope for Plutus.

But hopefully someone else will chime in!

On 11-Apr-19 3:33:27 PM, Rishav Pandey <notifications@github.com> wrote:
Is it possible to add a specific opening balance on either side of credit or debit. As per the docs we need to clear out the debit and credit total with different account.
Why this feature.
So moving to the erp developed on web is it possible to make an entry as opening amount from new Financial Year.
I can make a separate model that can handle this but I'm curious to know if this is present in library.

**Comment by vonchristian** [comment]
you can make an entry using the balances of the accounts from your Balance Sheet from preceding year as your starting balances.

**Comment by vonchristian** [comment]
you can make an entry using the balances of the accounts from your Balance Sheet from preceding year as your starting balances.

**Comment by mbulat** [comment]
I'm in agreement with the above. You'll always want to use entries with debits and credits to create opening balances. Sometimes you'll have to set a specific account as "contra" to do this. 

A good example is issuing stock and then adding cash to an account. Check out the example at https://github.com/mbulat/plutus#contra-accounts-and-complex-entries
