### ISSUE TITLE
Please remove jquery-ui/datepicker dependency.

### ISSUE THREAD

**Issue by vanboom** [mbulat/plutus#134]
Thanks for creating this outstanding accounting framework.  After some refactoring of our UI, we are not able to remove jquery-ui dependencies because of the requirement in application.js.  A accounting framework like this should not have UI dependencies such as this.  Suggest moving the UI engine into another gem.

**Comment by mbulat** [comment]
It’s already been removed. Please update your gem to 0.17.

**Comment by vanboom** [comment]
Unfortunately I am sitll on Rails 5.2.4.5.   Will continue to use my fork until we can get to Rails 6.  Thanks.
