### ISSUE TITLE
 Sprockets::Rails::Helper::AssetNotPrecompiledError in Plutus::Reports#balance_sheet

### ISSUE THREAD

**Issue by kirantpatil** [mbulat/plutus#159]
Plutus error with Rails 7 app:

 Showing /home/ubuntu/plutus/app/views/layouts/plutus/application.html.erb where line #6 raised:

Asset `plutus/application.css` was not declared to be precompiled in production.
Declare links to your assets in `app/assets/config/manifest.js`.

  //= link plutus/application.css

and restart your server

![sprockets helper](https://user-images.githubusercontent.com/1178055/195274550-176433de-b5a6-4d7a-8540-42148ac6ca1a.PNG)

**Comment by mbulat** [comment]
I've added the proper manifest for new Sprockets. See the note in the Readme. You'll also need to add the link in your app's main config/manifest.js
