### ISSUE TITLE
Account Statement

### ISSUE THREAD

**Issue by rmatovu987** [mbulat/plutus#166]
Hi, 

I need to get the statement of an account. I have tried searching everywhere but I have failed to find a solution.

If there's an existing way to get the statement of an account kindly guide me to it. 

Thanks

**Comment by mbulat** [comment]
If you're referring to a statement that reflects transactions you'd send to a customer, then you'd have to implement that on the invoice layer of your app. The Plutus statements are only for internal bookkeeping only.

**Comment by rmatovu987** [comment]
It's not necessarily about a statement to send to a customer. It's more of a statement to show how the balance of the account has accumulated over time or in a specific period of time. 
For example, if I have an expense account with a value of USD 1000, and I would like to see how this value accumulated, a statement would be very helpful. 
In addition, with an existing database where I have been saving entries without a commercial document, this statement would be very useful.

**Comment by mbulat** [comment]
Okay, I think something like a sub ledger view? For example a page that displays only "Accounts Payable" credits and debits? 

That would be a great addition. Right now there's only a basic income statement and balance sheet and then very basic roll up of accounts and entires. 

I can possible take a try at something like that in the future, or a pull request would also be welcome.

**Comment by rmatovu987** [comment]
Okay then. Let me see what I can do
