### ISSUE TITLE
Query account balances, as contextualized by a fixed set of entries

### ISSUE THREAD

**Issue by freerobby** [mbulat/plutus#53]
For auditing purposes, it would be useful to be able to query account balances not based on all entries, but based on a fixed set of them. For example, I have a vacation rental site based on Plutus where for any booking there are a handful of entries:
- Booking created
- Reservation payment made
- Security deposit payment made
- Booking completed (revenue recognized)
- Security deposit refunded

It would be nice to be able to pass in this set of entries and get back a set of account balances are zero-relative to these entries that were passed in. This would allow me to determine if a security deposit is owed back to the customer based on whether my "Deposits Held" balance is 0 or not for this method call.

@mbulat Do you have any thoughts on whether this should live in Plutus proper, and if so, where it might fit in architecturally? The approach that jumps out at me is to make a non-persistent (no ActiveRecord) model that is initialized with a set of entries and returns the related account balances. But, because all of the logic currently for determining a balance lives in the Account objects, this seems not ideal, as it would duplicate that logic to some degree. Curious if you have any thoughts here.

**Comment by mbulat** [comment]
My initial thought on this would be to keep it outside of Plutus. We do something similar, but we use the commercial_document field to tie related entries together. If some of the entries have separate commercial documents (like an invoice, receipt, etc), then I might suggest some kind of class that's a parent of those documents.

Any reason this approach wouldn't work?

**Comment by mbulat** [comment]
I'm going to go ahead and close this issue... please feel free to re-open if it's still an issue or you have other ideas. Thanks.
