### ISSUE TITLE
Controller Setup for Entries

### ISSUE THREAD

**Issue by vonchristian** [mbulat/plutus#57]
I've been trying to setup my controller to create an entry for my Cash and Wage model. Here's what I've got so far.

class Cash < Plutus::Asset
end

class Wage < Plutus::Liability

Now I've read the documentation but I don't know how to implement it in my code. Please help me. Thank you

entry = Plutus::Entry.new(
                :description => "Order placed for widgets",
                :date => Date.yesterday,
                :debits => [
                  {:account_name => "Cash", :amount => 100.00}],
                :credits => [
                  {:account_name => "Unearned Revenue", :amount => 100.00}])

**Comment by mbulat** [comment]
Best place for questions is the google group which can be found in the Readme. Thanks.
