### ISSUE TITLE
balance instance method giving ArgumentError Exception: wrong number of arguments (1 for 0) error

### ISSUE THREAD

**Issue by naiyyar** [mbulat/plutus#64]
When trying to generate an income statement between two date,
 calculate balance for an account between two dates then it's giving below error

`account.balance(:from_date => @from_date, :to_date => @to_date)`
here account is an instance of **Plutus:Asset**
*** ArgumentError Exception: wrong number of arguments (1 for 0)

**Comment by mbulat** [comment]
Sounds like you're using an old version. Please check that your version of Plutus is at least 12.2
