### ISSUE TITLE
:entry.date and Date.today

### ISSUE THREAD

**Issue by kjbkjb** [mbulat/plutus#67]
We have forked and imported the entire Plutus codebase into our project as we've added many features.

One thing we just ran into is the date range calculations have what I consider a slight problem. Depending on how you structure your work.

In the "Plutus::Entry#default_date" method, you use Date.today. Which we found is from Ruby and is based on local server time. All is reasonable to a point, however, if you wanted to match up several custom business document totals with those in the Entry table, you run into the fact that :created_at is in UTC in rails models.

https://github.com/mbulat/plutus/blob/master/app/models/plutus/entry.rb#L55

For our purposes, we will be changing this to Date.current, which is UTC based.

```
[3] pry(main)> Date.today
=> Wed, 11 May 2016
[4] pry(main)> Date.current
=> Thu, 12 May 2016
[5] pry(main)> DateTime.now
=> Wed, 11 May 2016 19:28:28 -0500
[6] pry(main)> DateTime.now.utc
=> Thu, 12 May 2016 00:28:33 +0000
[7] pry(main)> Plutus::Entry.last.created_at
  Plutus::Entry Load (0.4ms)  SELECT  `plutus_entries`.* FROM `plutus_entries`  ORDER BY `plutus_entries`.`created_at` ASC LIMIT 1
=> Thu, 12 May 2016 00:13:34 UTC +00:00
```

Close this issue if you think appropriate, but I wanted to at least raise it just in case.

**Comment by rosskevin** [comment]
@kjbkjb we use `Time.now` in our implementation.  Since you are bringing up the subject of UTC, you might consider using the time value instead of basic date if you are to support international clients.  `Time.now` (or any time based value) is not negotiable and points to the same moment in time, regardless of what date it falls on in different parts of the world.

**Comment by mbulat** [comment]
I do think it makes sense to default to how ActiveRecord creates timestamps. Looking at the code it uses TIme.now unless the default time zone is UTC..

https://github.com/rails/rails/blob/877ea784e4cd0d539bdfbd15839ae3d28169b156/activerecord/lib/active_record/timestamp.rb#L110

I'd probably update the Entry default_date to the same

    ActiveRecord::Base.default_timezone == :utc ? Time.now.utc : Time.now
