### ISSUE TITLE
Not having to "switch on" tenancy

### ISSUE THREAD

**Issue by ramontayag** [mbulat/plutus#68]
What do you think about not having to switch on tenancy? I found that having to do this complicated testing because the logic (and generated migrations) forks in a significant way.

@mbulat, what do you think about https://github.com/imacchiato/plutus/commit/99b66e6d43a96b6b388e88994608dcd4fa32d6de?

**Comment by mbulat** [comment]
I think I like the idea. I'm evaluating it at the moment, plus the updates to the rails engine. 

Do you have an example of how the tests were complicated due to the switch on tenancy?

**Comment by ramontayag** [comment]
@mbulat since the Tenancy module would be included during run time, we would not be able to unload it, unless we start two separate processes that have different configs.

**Comment by ramontayag** [comment]
Closing this. Discussion can be moved to https://github.com/mbulat/plutus/pull/79
