### ISSUE TITLE
Demo application or screenshots

### ISSUE THREAD

**Issue by holgersindbaek** [mbulat/plutus#69]
Is there a demo application somewhere online that I can mess around with? Maybe some screenshots, so I can get a quick first impression of the system?

**Comment by mbulat** [comment]
There's not much to screen shot as this is primarily a back-end system, though there is currently a simple income statement and balance sheet. 

I don't know of any demos, but maybe someone else does. The best place to ask general questions is the google group.

**Comment by holgersindbaek** [comment]
Ok... thanks for the quick response. I'm about to build out some internal bookkeeping for my company (an iOS marketplace), where we would like to keep better track of all the money that moves around in our system.

I'm still a bit new to bookkeeping/accounting. Seems like there are 5 main types you can file stuff under. Do you have any links to examples that I can look at? Any good links to accounting 101 in relation to where to file what?

**Comment by mbulat** [comment]
There's a link all the way at the bottom of the Readme to a text book I reference. I think used copies can be had on Amazon for a couple bucks. 

Eventually it would be nice to have a wiki here on GitHub with common practices and examples, but nothing is in the works at the moment.
