### ISSUE TITLE
Question : where are the create functions for example asset.create ?

### ISSUE THREAD

**Issue by rwobben** [mbulat/plutus#71]
Hello, 

I like this engine and maybe later I will try to make a sort of invoice system for a small company I work for, so I willl have a complete accounting system for that company

But my question is: where are the create . update functions of for example accounts.

**Comment by mbulat** [comment]
Please see the README for instructions on using the engine. All the models are basic ActiveRecord objects, so you should be familiar with them if you are familiar with Rails.

The README also has a link to the mailing list which is a better place to ask general questions.
