### ISSUE TITLE
Removing Entry#description presence validation?

### ISSUE THREAD

**Issue by ramontayag** [mbulat/plutus#78]
I intend to attach commercial documents, and setting a description would be redundant for me. What do you think about removing the validation?

**Comment by mbulat** [comment]
I might be open to it given that there is a check on having at least a commercial document associated if the description is left blank. That would at least prevent accidental entries that would be entirely untraceable.

**Comment by ramontayag** [comment]
Ok sounds good. I'll add it to my list of todos. Will close this in the mean time.
