### ISSUE TITLE
Issue when using jquery-ui >= 5.0.0

### ISSUE THREAD

**Issue by chuz93** [mbulat/plutus#80]
Hi. 
Congrats for Plutus! Its a great gem.

While i was using it, i found a bug with the assets. Digging a little bit i found that i was Plutus require jquery-ui gem i was using that gem in the 5.0.0 version. That version add a semanthic change from jquery.ui to jquery-ui.
Plutus is using in the application.css file the old semanthic 'jquery.ui.datepicker'.

**Comment by FX-HAO** [comment]
+1

**Comment by mbulat** [comment]
This is actually fixed in the master branch. A new gem version hasn't been pushed up to rubygems yet, so you can pull from github master for the time being. I'll try and get a new plutus version pushed to rubygems soon. Thanks.

See #58 for more details.

**Comment by mbulat** [comment]
Closing this.. should be fixed by #61
