### ISSUE TITLE
Trying to override model using decorator

### ISSUE THREAD

**Issue by Rudy-Zidan** [mbulat/plutus#82]
Hi guys, i am trying to validate account name to be unique i couldn't find it plutus so i tried to override account model and add this validation but doesn't work. Any one can tell me how i would be appreciated.
Thanks for your efforts.

**Comment by mbulat** [comment]
You should be able to override the account model. 

See http://guides.rubyonrails.org/engines.html#improving-engine-functionality

The mailing list is a better place to discuss this kind of thing... you can find it at

https://groups.google.com/d/forum/plutus-gem
