### ISSUE TITLE
Uninitialized constant Plutus::Entry

### ISSUE THREAD

**Issue by przbadu** [mbulat/plutus#89]
I am facing some wierd issue with latest version of plutus:

For the very first time, it does insert `Plutus::Assets`, `Plutus::Liability`, etc and If I call `Assets` or `Liability` for second time, it is giving uninitialized constant.

Please check below screencast for more detail:

![plutus-issue](https://cloud.githubusercontent.com/assets/4189129/23841708/4755c0d0-07d7-11e7-97f4-761bdcd0b77a.gif)

As you can see `Plutus::Entry` is raising `Uninitialized constant` error. Similarly, `Plutus::Assets`, `Plutus::Liability`, `Plutus::Revenue`, etc are inserting row for the very first time, and it again raise `Uninitialized constant` from second time.

Thanks

**Comment by faisal-bhatti** [comment]
I'm facing the same issue. Is this related with rails 5? Or rails 5 supported?

**Comment by przbadu** [comment]
@faisal-bhatti: right I am on rails 5 too 👍

**Comment by mordocai** [comment]
Yep, I'm not a contributor (just a watcher) but based on https://github.com/mbulat/plutus/pull/76 existing i'd say it doesn't work on rails 5.

**Comment by mbulat** [comment]
Yes.. this was due to not supporting Rails5. Please try out the new branch at https://github.com/mbulat/plutus/tree/rails5
