### ISSUE TITLE
`rails5` branch broken

### ISSUE THREAD

**Issue by singjsong** [mbulat/plutus#99]
[Line 24](https://github.com/mbulat/plutus/blob/de0fdaf490fe0e3cb846d35e3696ae31716279f2/plutus.gemspec#L24) reads:
```ruby
s.add_dependency("jquery-ui-rails", ">= 4.2.2")
```
Yet `4.2.2` does not exist, and the next version after that, `5.0.0`, uses a different folder structure for importing assets than what is used in [application.js](https://github.com/mbulat/plutus/tree/rails5/app/assets/javascripts/plutus).

**Comment by swrobel** [comment]
The latest release (0.13) supports Rails 5. You shouldn't need to use that branch.

**Comment by mbulat** [comment]
Yes... master branch and latest gem supports Rails 5.
